magento_import_dispatcher_supervisor_config_path: "/etc/supervisor.d/import_dispatcher.conf"
magento_import_dispatcher_supervisor_config_off_path: "/etc/supervisor.d/import_dispatcher.conf.off"
magento_import_dispatcher_switch_script_path: /usr/bin/import_dispatcher_switch