allow_duplicates: yes
dependencies: 
  - cs.repo-mageops

galaxy_info:
  author: Filip Sobalski <filip.sobalski@creativestyle.pl>
  description: nginx repository for CentOS
  company: creativestyle Polska
  license: license (BSD, MIT)
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions: [7]
  galaxy_tags:
    - nginx
    - webserver
    - server
    - http
    - proxy
    - repository
    - packages
    - rpm
    - mageops
    - magento
    - magesuite
    - creativestyle


