aws_cloudwatch_agent_package: amazon-cloudwatch-agent
aws_cloudwatch_exception_forwarder_package: aws-excfwd

aws_logs_project_root: "{{ magento_live_release_dir }}"
aws_logs_report_logger_rev: 876df02
aws_logs_stream_name: default

# Whether to use our custom handler to push magento reports to cloudwatch
aws_logs_log_magento_crash_reports: no

# The extra var is combined recursively with default loggers config.
# All loggers are disabled by defaults, so you can easily enable them by setting sth like:
# aws_logs_loggers_extra:
#   syslog:
#       enabled: yes
aws_logs_loggers: {}

# Retention time is in days with possible values in [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
aws_logs_loggers_default:
    syslog:
        group_name: "/syslog"
        filename: "/var/log/messages"
        date_format: "%b %-d %H:%M:%S"
        retention: 14
        multiline: no
        enabled: no
    magento-system:
        group_name: "/magento/system.log"
        filename: "{{ aws_logs_project_root }}/var/log/system.log"
        date_format: "[%Y-%m-%d %H:%M:%S]"
        retention: 30
        multiline: yes
        enabled: no
    magento-cron:
        group_name: "/magento/cron.log"
        filename: "{{ aws_logs_project_root }}/var/log/cron.log"
        date_format: "[%Y-%m-%d %H:%M:%S]"
        retention: 7
        multiline: yes
        enabled: no
    magento-debug:
        group_name: "/magento/debug.log"
        filename: "{{ aws_logs_project_root }}/var/log/debug.log"
        date_format: "[%Y-%m-%d %H:%M:%S]"
        retention: 7
        multiline: yes
        enabled: no
    magento-exception:
        group_name: "/magento/exception.log"
        filename: "{{ aws_logs_project_root }}/var/log/exception.log"
        date_format: "[%Y-%m-%d %H:%M:%S]"
        retention: 14
        multiline: yes
        enabled: no
    magento-paywithamazon:
        group_name: "/magento/paywithamazon.log"
        filename: "{{ aws_logs_project_root }}/var/log/paywithamazon.log"
        date_format: "[%Y-%m-%d %H:%M:%S]"
        retention: 60
        multiline: yes
        enabled: no
    nginx-access:
        group_name: "/nginx/access.log"
        filename: "{{ nginx_log_dir }}/access.log"
        date_format: "[%d/%b/%Y:%H:%M:%S %z]"
        retention: 3
        multiline: no
        enabled: no
    nginx-error:
        group_name: "/nginx/error.log"
        filename: "{{ nginx_log_dir }}/error.log"
        date_format: "%Y/%m/%d %H:%M:%S"
        retention: 7
        multiline: yes
        enabled: no
    php-fpm-error:
        group_name: "/php-fpm/php-fpm-backend-slow.log"
        filename: "{{ php_fpm_log_dir_path }}/php-fpm-backend-slow.log"
        date_format: "[%d-%b-%Y %H:%M:%S]"
        retention: 7
        multiline: no
        enabled: no
    php-cli-error:
        group_name: "/php-cli/php-cli-error.log"
        filename: "/var/log/php-cli-error.log"
        date_format: "[%d-%b-%Y %H:%M:%S"
        retention: 7
        multiline: no
        enabled: no
    postfix-maillog:
        group_name: "/postfix/maillog"
        filename: "/var/log/maillog"
        date_format: "[%b %d %H:%M:%S]"
        retention: 7
        multiline: no
        enabled: no
    elasticsearch-main:
        group_name: "/elasticsearch/node.log"
        filename: "/var/log/elasticsearch/{{ elasticsearch_cluster_name }}.log"
        date_format: "[%Y-%m-%dT%H:%M:%S"
        retention: 7
        multiline: yes
        enabled: no
    redis-server:
        group_name: "/redis/server.log"
        filename: "/var/log/redis/redis-server.log"
        date_format: "%d %b %H:%M:%S"
        retention: 7
        multiline: no
        enabled: no
    redis-sessions-server:
        group_name: "/redis/sessions-server.log"
        filename: "/var/log/redis/redis-sessions-server.log"
        date_format: "%d %b %H:%M:%S"
        retention: 7
        multiline: no
        enabled: no
    warmup-crawler:
        group_name: "/magento/warmup-crawler.log"
        filename: "{{ aws_logs_project_root }}/var/log/cache_warmer_crawler.log"
        date_format: "[%Y-%m-%d %H:%M:%S]"
        retention: 3
        multiline: yes
        enabled: no
    magento-report:
        group_name: "/magento/report"
        retention: 7
        enabled: "{{ aws_logs_log_magento_crash_reports }}"
    page-cache-misses:
        multiline: no
        group_name: "/nginx/page-cache-misses"
        filename: "{{ https_termination_page_cache_misses_logfile }}"
        date_format: "%d/%b/%Y:%H:%M:%S %z"
        retention: 7
        enabled: no
    varnish-purges:
        multiline: no
        group_name: "/varnish/purges"
        filename: "{{ varnish_purge_logfile }}"
        date_format: "[%a %b %d %H:%M:%S %Z %Y]"
        retention: 7
        enabled: no