- name: Fetch existing log groups
  shell: "aws logs describe-log-groups"
  register: aws_logs_describe

- name: Set log group list
  set_fact:
    aws_logs_log_group_names: "{{ (aws_logs_describe.stdout | from_json).logGroups | map(attribute='logGroupName')|list }}"

- name: Create missing log groups
  shell: "aws logs create-log-group --log-group-name=/{{ mageops_project }}/{{ mageops_environment }}{{ item.group_name }}"
  with_items: "{{ _aws_logs_loggers | default([]) }}"
  loop_control:
    label: "{{ item.group_name }}"
  when: item.enabled and not ('/' ~ mageops_project ~ '/' ~ mageops_environment ~ item.group_name) in aws_logs_log_group_names

- name: Set retention policy for log groups
  shell: "aws logs put-retention-policy --log-group-name=/{{ mageops_project }}/{{ mageops_environment }}{{ item.group_name }} --retention-in-days={{ item.retention }}"
  when: item.enabled
  loop_control:
    label: "{{ item.group_name }}"
  with_items: "{{ _aws_logs_loggers | default({}) }}"
