- name: "Create directory for domain redirect"
  file:
    path: "{{ nginx_serverd_dir }}/{{ item.value }}"
    state: directory
    recurse: yes
    owner: root
    group: root

- name: "Generate server config for domain redirect"
  template:
    src: language-redirect-domain.conf.j2
    dest: "{{ nginx_serverd_dir }}/{{ item.value }}/{{ nginx_language_redirect_conf_filename }}"
  with_dict: "{{ nginx_language_redirect_domain_mapping }}"
  notify:
    - Apply final nginx config

- name: Register provisioned nginx config files
  set_fact:
    nginx_config_cleanup_provisioned_files: >-
      {{
         nginx_config_cleanup_provisioned_files
         + [ nginx_serverd_dir ~ '/' ~ item.value ~ '/' ~ nginx_language_redirect_conf_filename ]
      }}
  with_dict: "{{ nginx_language_redirect_domain_mapping }}"
