allow_duplicates: yes
dependencies: 
  - cs.repo-mageops

galaxy_info:
  author: Filip Sobalski <filip.sobalski@creativestyle.pl>
  description: Remi's repository for CentOS
  company: creativestyle Polska
  license: license (BSD, MIT)
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions: [7]
  galaxy_tags:
    - repository
    - packages
    - rpm
    - mageops
    - magento
    - magesuite
    - rhel
    - redhat
    - creativestyle
    - php
    - php-fpm
    - remi


