allow_duplicates: no
dependencies: 
  - cs.repo-epel

galaxy_info:
  author: Filip Sobalski <filip.sobalski@creativestyle.pl>
  description: MageOps repository for CentOS
  company: creativestyle Polska
  license: license (BSD, MIT)
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions: [7]
  galaxy_tags:
    - repository
    - packages
    - rpm
    - mageops
    - magento
    - magesuite
    - creativestyle


