mageops_migrations_deprecated_yum_repos:
  - varnishcache_varnish41
  - szpadel-centos-extras
  - elasticsearch-5.x

mageops_migrations:
  - title: Make sure deprecated repositories are absent
    name: repository

  - title: Make sure old incompatible awsci package and its leftovers are absent
    name: awscli

  - title: Python PIP fixes for urllib
    name: urllib3

  - title: Renamed nginx configs
    name: nginx-config

  - title: Old elasticsearch prov
    name: elasticsearch

  - title: Old custom nginx packages
    name: nginx-creativeshop

  - title: Python OpenSSL/Cryptography modules
    name: python-openssl