- name: Configure Magento environment (env.php)
  block:
  - name: Enable HTTP cache
    when: magento_http_cache_enable
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_app_etc_config_http_cache, recursive=true) }}

  - name: Enable ElasticSuite configuration
    when: elasticsuite_version | default(false, true)
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_app_etc_config_elasticsuite, recursive=true) }}

  - name: Configure Redis caching
    when: magento_redis_cache
    block:
    - name: Enable default Redis cache
      when: not magento_redis_cache_l2
      set_fact:
        magento_app_etc_config: >-
          {{ magento_app_etc_config
              | combine(magento_app_etc_config_cache_default_redis, recursive=true) }}

    - name: Enable 2-level default Redis cache
      when: magento_redis_cache_l2
      set_fact:
        magento_app_etc_config: >-
          {{ magento_app_etc_config
              | combine(magento_app_etc_config_cache_default_redis_l2, recursive=true) }}

    - name: Configure Redis page cache
      set_fact:
        magento_app_etc_config: >-
          {{ magento_app_etc_config
              | combine(magento_app_etc_config_cache_page_redis, recursive=true) }}

  - name: Enable RabbitMQ queue configuration
    when: magento_rabbitmq_queue
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_app_etc_config_queue_rabbitmq, recursive=true) }}

  - name: Adjust configuration for consumer workers
    when: magento_consumer_workers_enable
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_app_etc_config_consumer_workers, recursive=true) }}

  - name: Adjust configuration for cron consumers
    when: magento_cron_consumers_enable
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_app_etc_config_cron_consumers, recursive=true) }}

  - name: Configure X-Magento-Vary cookie signing
    when: magento_vary_sign
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_app_etc_config_cookie_sign, recursive=true) }}

  - name: Enable mysql ssl requirement
    when: mageops_mysql_require_ssl
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_mysql_ssl_required, recursive=true) }}

  - name: Set extra options
    set_fact:
      magento_app_etc_config: >-
        {{ magento_app_etc_config
            | combine(magento_app_etc_config_extra, recursive=true) }}

  - name: Export configuration as PHP code
    command:
      stdin: "{{ magento_app_etc_config | to_json }}"
      argv:
      - php
      - -r
      - >-
        echo "<?php \n\n"; echo "return ";

        $data = json_decode(
          file_get_contents("php://stdin"),
          true
        );

        if (false === $data) {
          fwrite(STDOUT, json_last_error_msg());
          exit(json_last_error());
        }

        var_export($data);

        echo "; \n\n";
    changed_when: false
    register: magento_app_enc_config_export

  - name: Install configuration file
    copy:
      content: "{{ magento_app_enc_config_export.stdout }}"
      dest: "{{ magento_release_dir }}/app/etc/env.php"
      owner: "{{ magento_user }}"
      group: "{{ magento_group }}"
      mode: 0640
      force: 1
