#- name: Ensure project database exists
#  mysql_db:
#    login_host: "{{ mageops_mysql_host }}"
#    login_user: "{{ mageops_mysql_root_user }}"
#    login_password: "{{ mageops_mysql_root_pass }}"
#    name: "{{ mageops_app_mysql_db }}"
#    state: present

#- name: Ensure project db user for external connections exists
#  mysql_user:
#    login_host: "{{ mageops_mysql_host }}"
#    login_user: "{{ mageops_mysql_root_user }}"
#    login_password: "{{ mageops_mysql_root_pass }}"
#    user: "{{ mageops_app_mysql_user }}"
#    password: "{{ mageops_app_mysql_pass }}"
#    host: "%"
#    state: present
#    priv: "{{ mageops_app_mysql_db }}.*:{{ mysql_configure_all_db_permissions }}"

- name: Ensure project db user for localhost exists
  mysql_user:
    login_host: "{{ mageops_mysql_host }}"
    login_user: "{{ mageops_mysql_root_user }}"
    login_password: "{{ mageops_mysql_root_pass }}"
    user: "{{ mageops_app_mysql_user }}"
    password: "{{ mageops_app_mysql_pass }}"
    host: "localhost"
    state: present
    priv: "{{ mageops_app_mysql_db }}.*:{{ mysql_configure_all_db_permissions }}"
  when: mysql_user_localhost_access
