- name: Gather policies to process
  set_fact:
    aws_s3_bucket_policies: "{{ aws_s3_bucket_policies_default + aws_s3_bucket_policies }}"

- name: Gather bucket names to process
  set_fact:
    aws_s3_bucket_names: "{{ aws_s3_bucket_policies | map(attribute='bucket')|list | unique }}"

- name: Create temporary s3 bucket policy build directory
  tempfile:
    state: directory
    suffix: build
  register: aws_s3_temp_dir

- name: Build s3 bucket policies
  template:
    src: bucket-policy.json.j2
    dest: "{{ aws_s3_temp_dir.path }}/bucket-policy-{{ item }}.json"
  with_items: "{{ aws_s3_bucket_names }}"

- name: Set s3 bucket policies
  shell: "aws s3api put-bucket-policy --bucket={{ item }} --policy=file://{{ aws_s3_temp_dir.path }}/bucket-policy-{{ item }}.json"
  with_items: "{{ aws_s3_bucket_names }}"